# Generated by Django 6.0 on 2025-12-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinchan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
