# Generated by Django 6.0 on 2025-12-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinchan', '0002_department_name_department_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('branch', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('gender', models.CharField(max_length=1)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('cgpa', models.FloatField()),
                ('attendance', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('scholarship', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='department',
        ),
    ]
